/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package data.structures;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        NodeList<Integer> n;
        System.out.println(new App().getGreeting());
    }
}
